### ISSUE TITLE
Show currently running database and disable the "Play" button if there is none.

### ISSUE THREAD

**Issue by jexp** [neo4j-apps/graph-examples#1]

**Comment by nossila** [comment]
@jexp can you suggest a way to effectively get the current project? Right know `neo4jDesktopApi.getContext` returns a context with a list of projects which don't say anything if thats the selected project or another one.

**Comment by jexp** [comment]
please also listen to the context updates:
https://github.com/neo4j-apps/graph-app-starter#quickstart-example

**Comment by whatSocks** [comment]
updated
